name: Test

on: push

jobs:
  test-std140:
    name: Test std140
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby 2.0        # Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # Install modelkit
      - name: Setup python anaconda       # Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      # Install: pip install openpyxl
      - name: Install Openpyxl
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            openpyxl
      - name: Run-test
        run: rake
      - name: Upload executable artifiact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 
          path: 