name: Test

on: push

jobs:
  test-std140:
    name: Test std140
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download & Install modelkit  # Install modelkit
        run: |
          curl -o modelkit-installer.exe https://share.bigladdersoftware.com/files/modelkit-caboodle-0.9.0-flannel+caboodle.22.a701d43.exe
          .\modelkit-installer.exe /SP- /VERYSILENT /DIR=modelkit-folder
      - name: Add modelkit to path
        run: |
          "${{ github.workspace }}\modelkit-folder\bin" >> $env:GITHUB_PATH
      - name: Check directories
        run: |
          echo $env:path
          dir
          dir cases
          dir "${{ github.workspace }}\modelkit-folder"
          dir "${{ github.workspace }}\modelkit-folder\bin"
      - name: Test modelkit command
        run: modelkit --version
      - name: Create template for single case
        run: |
          mkdir tempCase
          dir "${{ github.workspace }}\base-section-5.pxt"
          modelkit template-compose ".\\base-section-5.pxt"
          dir "${{ github.workspace }}\tempCase"
      - name: Run rake test
        run: |
          modelkit rake