name: Test

on: push

jobs:
  test-std140:
    name: Test std140
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modelkit  # Install modelkit
        run: |
          curl https://share.bigladdersoftware.com/files/modelkit-caboodle-0.9.0-flannel+caboodle.22.a701d43.exe --output ./modelkit-installer.exe
          .\modelkit-installer.exe /SP- /VERYSILENT /DIR=.\modelkit-folder
      - name: Add modelkit to path
        run: |
          "${{ github.workspace }}\modelkit-folder\bin" >> $env:GITHUB_PATH
      - name: Test modelkit help
        run: |
          echo $env:path
          dir
          dir "${{ github.workspace }}\modelkit-folder"
          dir "${{ github.workspace }}\modelkit-folder\bin"
          .\modelkit-folder\bin\modelkit.bat
          modelkit --version
          modelkit --help
      - name: Run rake test
        run: |
          modelkit rake