name: Test

on: push

jobs:
  test-std140:
    name: Test std140
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: action/checkout@1
      - name: Set up Ruby 2.6         # Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x   
      # Install modelkit
      - name: Setup python anaconda       # Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      # Install: pip install openpyxl
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
      - name: Install openpyxl
        run: pip install openpyxl
      - name: Run-test
        run: rake
      - name: Upload executable artifiact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 
          path: 