name: Test

on: push

jobs:
  test-std140:
    name: Test std140
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modelkit  # Install modelkit
        run: |
          curl https://share.bigladdersoftware.com/files/modelkit-caboodle-0.9.0-flannel+caboodle.22.a701d43.exe --output ./modelkit-installer.exe
          mkdir modelkit-folder
          modelkit-installer.exe /VERYSILENT /DIR=./modelkit-folder/
      # - name: Add modelkit to path
      #   run: echo "${HOME}/modelkit-folder/bin/modelkit.bat" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Test path
        run: |
          PATH
      # $GITHUB_PATH
      - name: Run-test
        run: rake
      #cd modelkit-folder
        #cd bin
        #dir
        #modelkit.bat --help
      # modelkit --help
      # https://share.bigladdersoftware.com/files/modelkit-caboodle-0.9.0-flannel+caboodle.22.a701d43.exe
      # https://download.bigladdersoftware.com/?ref=modelkit-catalyst-latest-win
      #- name: Upload executable artifiact
      #  uses: actions/upload-artifact@v2.2.4
      #  with:
      #    name: 
      #    path: 